### ISSUE TITLE
node mirror can not access

### ISSUE THREAD

**Issue by muzi131313** [cnpm/binary-mirror-config#30]
visit  [package.json#L49](https://github.com/cnpm/binary-mirror-config/blob/master/package.json#L49),
result as below:
![image](https://user-images.githubusercontent.com/2398149/166130228-47e3dd42-f326-468e-b113-5b78c19f690f.png)
otherwise this [address](https://registry.npmmirror.com/binary.html?path=node/) is okay
```
https://registry.npmmirror.com/binary.html?path=node/
```
article from [here](https://antfu.me/posts/npm-binary-mirrors)

**Comment by fengmk2** [comment]
use https://npmmirror.com/mirrors/node/ instead
