### ISSUE TITLE
sqlite3@v5.1.4 binary 镜像同步的问题

### ISSUE THREAD

**Issue by AngusFu** [cnpm/binary-mirror-config#43]
没有同步到 `napi-v3-linux-glibc-arm64.tar.gz` 这个 release 

- https://registry.npmmirror.com/binary.html?path=sqlite3/v5.1.4/
- https://github.com/TryGhost/node-sqlite3/releases

https://registry.npmmirror.com/binary.html?path=sqlite3/v5.1.4/

![image](https://user-images.githubusercontent.com/8180186/209048381-97ead70f-6bbf-46ba-8201-fd60ca016ee2.png)
![image](https://user-images.githubusercontent.com/8180186/209048422-8026e650-d7c3-42b5-ba6f-79bf527b9a7c.png)

**Comment by fengmk2** [comment]
已经触发重新同步，稍等。

**Comment by AngusFu** [comment]
@fengmk2 感谢   已确认同步好了 
![image](https://user-images.githubusercontent.com/8180186/209076233-10215baa-b1eb-403a-a577-061264924eb8.png)
