### ISSUE TITLE
ELECTRON_MIRROR 地址错误

### ISSUE THREAD

**Issue by aimer-fan** [cnpm/binary-mirror-config#45]
项目里配置的 `ELECTRON_MIRROR` 是 `https://cdn.npmmirror.com/binaries/electron/`，但是官网上给的代理地址是 `https://npmmirror.com/mirrors/electron/`。

[文档地址](https://www.electronjs.org/zh/docs/latest/tutorial/installation#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%95%9C%E5%83%8F%E5%92%8C%E7%BC%93%E5%AD%98)

**Comment by fengmk2** [comment]
两者是等价的，是遇到什么问题了吗？

**Comment by aimer-fan** [comment]
我昨天使用 https://cdn.npmmirror.com/binaries/electron/ 这个地址下载的时候总是失败，换成 https://npmmirror.com/mirrors/electron/ 这个就可以了，所以感觉是地址错误了。

如果是等价的话，可能是我的网络问题。
